mkdir -p ~/.config/i3/
cp ~/home/dotfiles/i3-config ~/.config/i3/config
mkdir -p ~/.config/gsimplecal/
cp ~/home/dotfiles/gsimplecal-config  ~/.config/gsimplecal/config
cp gnome-control-center.desktop ~/.local/share/applications
mkdir -p ~/.config/Code/User
cp vscode-settings.json ~/.config/Code/User/settings.json
mkdir -p ~/.config/kitty/
cp kitty.conf ~/.config/kitty/kitty.conf
